# Generated by Django 5.0.3 on 2024-04-03 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='anonymous', max_length=200, verbose_name='שם')),
                ('email', models.EmailField(max_length=200, null=True, verbose_name='אימייל')),
                ('topic', models.CharField(max_length=300, verbose_name='נושא')),
                ('description', models.CharField(max_length=1000, verbose_name='תיאור')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='תאריך')),
            ],
            options={
                'verbose_name_plural': 'פורום',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discuss', models.TextField(blank=True, default=None, max_length=5000, verbose_name='התגובה')),
                ('name', models.CharField(blank=True, default=None, max_length=100, verbose_name='שם')),
                ('forum', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.forum', verbose_name='הנושא עליו תרצה להגיב')),
            ],
            options={
                'verbose_name_plural': 'דיונים',
            },
        ),
    ]
