# Generated by Django 5.0.3 on 2024-04-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'verbose_name_plural': 'תגובות לבקשות תרומה'},
        ),
        migrations.AlterModelOptions(
            name='forum',
            options={'verbose_name_plural': 'בקשות תרומה'},
        ),
        migrations.AlterField(
            model_name='forum',
            name='description',
            field=models.TextField(blank=True, default=None, verbose_name='תיאור'),
        ),
    ]
