# Generated by Django 5.0.3 on 2024-04-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_discussion_options_alter_forum_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(default='אנונימי', max_length=200, verbose_name='שם'),
        ),
    ]
