# Generated by Django 5.0.3 on 2024-03-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid_org', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aid_org',
            new_name='AidOrg',
        ),
    ]
