# Generated by Django 5.0.3 on 2024-03-08 01:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_org', '0002_rename_aid_org_aidorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidorg',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
