# Generated by Django 5.0.3 on 2024-03-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_org', '0003_aidorg_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidorg',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
