# Generated by Django 5.0.3 on 2024-03-12 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_org', '0004_aidorg_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidorg',
            name='image',
            field=models.ImageField(default='', upload_to='aid_org_images'),
        ),
    ]
