# Generated by Django 5.0.3 on 2024-03-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid_org', '0005_aidorg_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidorg',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
