# Generated by Django 5.0.3 on 2024-04-02 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid_org', '0006_aidorg_thumb'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aidorg',
            options={'verbose_name_plural': 'ארגוני סיוע'},
        ),
        migrations.RemoveField(
            model_name='aidorg',
            name='image',
        ),
        migrations.RemoveField(
            model_name='aidorg',
            name='logo',
        ),
    ]
