# Generated by Django 5.0.3 on 2024-03-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='שם')),
                ('id_number', models.CharField(max_length=100, verbose_name='תעודת זהות')),
                ('credit_number', models.CharField(blank=True, max_length=100, verbose_name='מספר אשראי')),
                ('cvc', models.CharField(blank=True, max_length=100, verbose_name='3 ספרות מאחורי הכרטיס')),
                ('amount', models.CharField(max_length=100, verbose_name='סכום')),
            ],
            options={
                'verbose_name_plural': 'תרומות',
            },
        ),
    ]
