# Generated by Django 5.0.3 on 2024-04-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hostReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='שם ושם משפחה ')),
                ('address', models.CharField(max_length=100, verbose_name='כתובת מלאה ')),
                ('housetype', models.CharField(max_length=15, verbose_name='סוג הנכס ')),
                ('rooms', models.IntegerField(verbose_name='מספר חדרים ')),
                ('beds', models.IntegerField(verbose_name='מספר מיטות ')),
                ('kosher', models.BooleanField(verbose_name='כשרות ')),
                ('phone', models.CharField(max_length=10, verbose_name='טלפון ')),
                ('email', models.EmailField(max_length=100, verbose_name='אימייל ')),
                ('description', models.TextField(blank=True, verbose_name='תיאור הנכס ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hostReq/', verbose_name='תמונה של הנכס ')),
            ],
            options={
                'verbose_name_plural': 'בקשות אירוח',
            },
        ),
        migrations.DeleteModel(
            name='YourModelName',
        ),
    ]
