# Generated by Django 5.0.3 on 2024-04-05 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_hostreq_delete_yourmodelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostreq',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
