# Generated by Django 5.0.3 on 2024-04-07 12:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0003_hostreq_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostreq',
            name='address',
        ),
        migrations.AddField(
            model_name='hostreq',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='עיר '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hostreq',
            name='street',
            field=models.CharField(default=1, max_length=100, verbose_name='רחוב '),
            preserve_default=False,
        ),
    ]
