# Generated by Django 5.0.3 on 2024-04-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0004_remove_hostreq_address_hostreq_city_hostreq_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostreq',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='רחוב '),
        ),
    ]
