# Generated by Django 5.0.3 on 2024-04-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0005_alter_hostreq_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostreq',
            name='image',
        ),
        migrations.AddField(
            model_name='hostreq',
            name='thumb',
            field=models.ImageField(blank=True, default='download.png', upload_to='media/', verbose_name='תמונה של הנכס '),
        ),
    ]
