# Generated by Django 5.0.3 on 2024-04-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0007_alter_hostreq_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostreq',
            name='is_occupied',
            field=models.BooleanField(default=False, verbose_name='האם הנכס תפוס'),
        ),
    ]
